version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../api:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres

  api-test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    volumes:
      - ../api:/usr/src/app
    environment:
      DB_HOST: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres
    command: npm test

  front:
    build:
      context: ../
      dockerfile: docker/Dockerfile.front
    volumes:
      - ../front:/usr/src/app
    ports:
      - "3001:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FAST_REFRESH: "false"
    depends_on:
      - api
